version: '3'
services:
  piseth:
    image: docker_piseth:latest
    container_name: piseth
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3206:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    networks:
      - data_analytics
networks:
  data_analytics: data_analytics
  external: true